# Development Environment Configuration
name: development
description: Development environment for Shield AI

# Environment variables for development
environment:
  NODE_ENV: development
  NEXT_PUBLIC_ENVIRONMENT: development
  NEXT_PUBLIC_APP_URL: https://dev-shieldai.vercel.app
  
# Deployment settings
deployment:
  # Auto-deploy on dev branch pushes
  auto_deploy: true
  branch: dev
  
  # Vercel settings
  vercel:
    alias: dev-shieldai
    build_env:
      - NEXT_PUBLIC_SUPABASE_URL
      - NEXT_PUBLIC_SUPABASE_ANON_KEY
      - NEXT_PUBLIC_STRIPE_PUBLISHABLE_KEY
      - NEXT_PUBLIC_VAPID_PUBLIC_KEY
    
# Review settings
review:
  # Require approval for manual deployments
  required_reviewers: 0
  
# Protection rules
protection:
  # Allow any collaborator to deploy to dev
  required_status_checks: []
  enforce_admins: false

# Monitoring
monitoring:
  health_check_url: https://dev-shieldai.vercel.app/api/health
  uptime_checks: true
  performance_monitoring: true

# Features enabled in development
features:
  debug_mode: true
  analytics: false
  error_reporting: true
  feature_flags: true