# Production Environment Configuration
name: production
description: Production environment for Shield AI

# Environment variables for production
environment:
  NODE_ENV: production
  NEXT_PUBLIC_ENVIRONMENT: production
  NEXT_PUBLIC_APP_URL: https://shieldai.vercel.app
  
# Deployment settings
deployment:
  # Manual deploy only for production
  auto_deploy: false
  branch: prod
  
  # Vercel settings
  vercel:
    alias: shieldai
    production: true
    build_env:
      - NEXT_PUBLIC_SUPABASE_URL
      - NEXT_PUBLIC_SUPABASE_ANON_KEY
      - NEXT_PUBLIC_STRIPE_PUBLISHABLE_KEY
      - NEXT_PUBLIC_VAPID_PUBLIC_KEY
      - OPENAI_API_KEY
      - STRIPE_SECRET_KEY
      - STRIPE_WEBHOOK_SECRET
      - SUPABASE_SERVICE_ROLE_KEY
      - API_BIBLE_KEY
      - PINECONE_API_KEY
      - PINECONE_ENVIRONMENT
    
# Review settings
review:
  # Require multiple approvals for production deployments
  required_reviewers: 2
  required_review_from_codeowners: true
  dismiss_stale_reviews: true
  
# Protection rules
protection:
  # Strict protection for production
  required_status_checks:
    - test
    - security
    - quality
    - build-test
    - e2e-tests
  enforce_admins: true
  restrict_pushes: true
  required_linear_history: true

# Monitoring
monitoring:
  health_check_url: https://shieldai.vercel.app/api/health
  uptime_checks: true
  performance_monitoring: true
  error_tracking: true
  alerting: true
  sla_monitoring: true

# Features enabled in production
features:
  debug_mode: false
  analytics: true
  error_reporting: true
  feature_flags: false
  security_headers: true
  rate_limiting: true
  
# Testing configuration
testing:
  smoke_tests: true
  health_checks: true
  performance_monitoring: true
  
# Backup and disaster recovery
backup:
  database_backups: true
  asset_backups: true
  configuration_backups: true
  
# Security settings
security:
  security_headers: true
  content_security_policy: strict
  rate_limiting: enabled
  ddos_protection: enabled
  ssl_enforcement: true
  
# Performance
performance:
  cdn: enabled
  caching: aggressive
  compression: enabled
  image_optimization: enabled